<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Progress_dot</name>
   <tag></tag>
   <elementGuidId>2269b08b-363d-439b-8c4d-c6dec67adf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tmln.tmln1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tmln tmln1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-package  delievry-settings  pace-done&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;delivery-top-sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;checkout-top-processbar&quot;]/div[@class=&quot;order-prcs-tmln-sec active2&quot;]/span[@class=&quot;tmln tmln1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
   </webElementXpaths>
</WebElementEntity>
